Employee.create!([
  {first_name: "Chris", last_name: "Carlson", business_email: "c.s.carlson6@gmail.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4563321551", extension: "10", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: true, password: "password"},
  {first_name: "Joe", last_name: "Doe", business_email: "jd@co.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4566694554", extension: "3", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password: "password"},
  {first_name: "Jane", last_name: "Doe", business_email: "JaneDoe@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4567892144", extension: "45", home_phone: "N/A", department: "Engineering", office_number: "23", location: "N/A", notes: nil, manager_id: nil, admin: false, password: "password"},
  {first_name: "Daenarys", last_name: "Targaryan", business_email: "D.Targaryan@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4568856336", extension: "12", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password: "password"},
  {first_name: "Sansa", last_name: "Stark", business_email: "SansaStark@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4568878686", extension: "23", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password: "password"},
  {first_name: "Jon", last_name: "Snow", business_email: "jonsnow@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4562213566", extension: "02", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password: "password"},
  {first_name: "Tyrion", last_name: "Lannaster", business_email: "tlann@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4562879633", extension: "5", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password: "password"},
  {first_name: "Petyr ", last_name: "Baelish", business_email: "petyrbaelish@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4561728933", extension: "56", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password: "password"}
])
