Employee.create!([
  {first_name: "Chris", last_name: "Carlson", business_email: "c.s.carlson6@gmail.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4563321551", extension: "10", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: true, password_digest: "$2a$10$hBvJpwb117ERsi2lY/ng5.k5v2nh8WPVSOeYkTGRXVqDt53nUaLcm", salt: "$2a$10$hBvJpwb117ERsi2lY/ng5."},
  {first_name: "Joe", last_name: "Doe", business_email: "jd@co.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4566694554", extension: "3", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password_digest: "$2a$10$218M3Zdgi.PpnP0OE1dDdeuqiV3O3UMrFPCvPIy7CUJi/w0FyVVgG", salt: "$2a$10$218M3Zdgi.PpnP0OE1dDde"},
  {first_name: "Jane", last_name: "Doe", business_email: "JaneDoe@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4567892144", extension: "45", home_phone: "N/A", department: "Engineering", office_number: "23", location: "N/A", notes: nil, manager_id: nil, admin: false, password_digest: "$2a$10$ww81yKdJMwaBNMkL4ptH/OLWRINd4J9dY8plDnEdE7uyPBQ/7vzhO", salt: "$2a$10$ww81yKdJMwaBNMkL4ptH/O"},
  {first_name: "Daenarys", last_name: "Targaryan", business_email: "D.Targaryan@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4568856336", extension: "12", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password_digest: "$2a$10$2GCeKZ1RPas3gu0xoEU5Fuy5GmzD830aGsOMsPk.27T8kccLYvPfG", salt: "$2a$10$2GCeKZ1RPas3gu0xoEU5Fu"},
  {first_name: "Sansa", last_name: "Stark", business_email: "SansaStark@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4568878686", extension: "23", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password_digest: "$2a$10$RHSFLMKEIk1ro82DxfdAG.bNiaQOm4FaRJhKEavkG2QsPNDYhA0EG", salt: "$2a$10$RHSFLMKEIk1ro82DxfdAG."},
  {first_name: "Jon", last_name: "Snow", business_email: "jonsnow@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4562213566", extension: "02", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password_digest: "$2a$10$BB0KJ/AcqP3M3SHLh14psO9bgwYEh5Diha9o1jHW6/Qjp9.1gQJTi", salt: "$2a$10$BB0KJ/AcqP3M3SHLh14psO"},
  {first_name: "Tyrion", last_name: "Lannaster", business_email: "tlann@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4562879633", extension: "5", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password_digest: "$2a$10$/6MJ10MJ/BZLe5JMhln.l.9LVS/SBkrLg7hI4JYizFf52858aUwIO", salt: "$2a$10$/6MJ10MJ/BZLe5JMhln.l."},
  {first_name: "Petyr ", last_name: "Baelish", business_email: "petyrbaelish@company.com", personal_email: "N/A", cell_phone: "N/A", business_phone: "4561728933", extension: "56", home_phone: "N/A", department: "N/A", office_number: "N/A", location: "N/A", notes: nil, manager_id: nil, admin: false, password_digest: "$2a$10$Zi51j0ZIwbR.7DC1zRhZCeUrHiGhhdmpvxZazNsW7mpXblBNt5mOO", salt: "$2a$10$Zi51j0ZIwbR.7DC1zRhZCe"}
])
